<?php
/**
 * @var \MageWorx\OptionFeatures\Block\Product\View\Wrapper $block
 */
?>
<script type="text/javascript">
    document.addEventListener('breeze:load', () => {
        const optionAdditionalImages = $.fn.mageworxOptionAdditionalImages.bind($.fn);

        var optionBase = window.mageworxOptionBase;

        if (optionBase) {
            optionBase.addUpdater(60, optionAdditionalImages(<?= /* @noEscape */ $block->getAllOptionsJson();?>));
        } else {
            var updaters = window.mageworxOptionUpdaters;
            if (!updaters) {
                updaters = {};
            }
            updaters[60] = optionAdditionalImages(<?= /* @noEscape */ $block->getAllOptionsJson();?>);
            window.mageworxOptionUpdaters = updaters;
        }
    });
</script>